alert_threshold: 40

input_paths:
  entities: data/synthetic_entity.csv
  transactions: data/synthetic_trx.csv
  wires: data/synthetic_wires.csv

output_paths:
  alerted_accounts: results/alerted_accounts.csv
  flagged_transactions: results/flagged_transactions.csv

rules:
  large_wire_transfers_followed_by_outgoing:
    thresholds: [1, 2, 3]
    scores: [5, 10, 15]
  
  sanctioned_countries_transactions:
    thresholds: [1, 3, 5]
    scores: [5, 10, 15]
  
  split_cash_deposits_same_day:
    thresholds: [1, 2, 3]
    scores: [3, 7, 10]
  
  suspected_money_mules:
    thresholds: [1, 2, 3]
    scores: [4, 8, 12]
  
  frequent_email_wire_transfers:
    thresholds: [5, 10, 15]
    scores: [4, 8, 12]
  
  mixed_funds_between_accounts:
    thresholds: [1, 2, 3]
    scores: [3, 6, 10]
  
  high_volume_deposits:
    thresholds: [5, 10, 15]
    scores: [3, 6, 10]
  
  structured_deposits_below_threshold:
    thresholds: [2, 3, 4]
    scores: [4, 8, 12]
  
  quick_withdrawals_after_deposits:
    thresholds: [2, 3, 4]
    scores: [4, 8, 12]
  
  foreign_exchange_wires:
    thresholds: [1, 2, 3]
    scores: [3, 6, 10]
  
  inconsistent_activity:
    thresholds: [1, 2, 3]
    scores: [4, 8, 12]

# Bonus de score si l'entité a été précédemment signalée comme suspecte
prior_suspicious_flag_boost: 20

# Paramètres de détection supplémentaires
detection_params:
  suspicious_countries: ['Iran', 'Emirats Arabes Unis', 'Koweit', 'Hong Kong', 'Chine']
  threshold_amount: 10000
  margin: 1000
  max_score: 100

simulation:
  param_grid:
    rules:
      large_wire_transfers_followed_by_outgoing:
        thresholds: [[1, 2, 3], [2, 3, 4]]
        scores: [[5, 10, 15], [7, 12, 18]]
      sanctioned_countries_transactions:
        thresholds: [[1, 3, 5], [2, 4, 6]]
        scores: [[5, 10, 15], [7, 12, 18]]
      split_cash_deposits_same_day:
        thresholds: [[1, 2, 3], [2, 3, 4]]
        scores: [[3, 7, 10], [5, 9, 12]]
      suspected_money_mules:
        thresholds: [[1, 2, 3], [2, 3, 4]]
        scores: [[4, 8, 12], [6, 10, 14]]
      frequent_email_wire_transfers:
        thresholds: [[5, 10, 15], [7, 12, 17]]
        scores: [[4, 8, 12], [6, 10, 14]]
      mixed_funds_between_accounts:
        thresholds: [[1, 2, 3], [2, 3, 4]]
        scores: [[3, 6, 10], [5, 8, 12]]
      high_volume_deposits:
        thresholds: [[5, 10, 15], [7, 12, 17]]
        scores: [[3, 6, 10], [5, 8, 12]]
      structured_deposits_below_threshold:
        thresholds: [[2, 3, 4], [3, 4, 5]]
        scores: [[4, 8, 12], [6, 10, 14]]
      quick_withdrawals_after_deposits:
        thresholds: [[2, 3, 4], [3, 4, 5]]
        scores: [[4, 8, 12], [6, 10, 14]]
      foreign_exchange_wires:
        thresholds: [[1, 2, 3], [2, 3, 4]]
        scores: [[3, 6, 10], [5, 8, 12]]
      inconsistent_activity:
        thresholds: [[1, 2, 3], [2, 3, 4]]
        scores: [[4, 8, 12], [6, 10, 14]]
    prior_suspicious_flag_boost: [15, 20, 25]
  
  evaluation_metric: "f1_score" 